services:
  sonar:
    container_name: "sonar"
    entrypoint:
      - "/opt/sonarqube/docker/entrypoint.sh"
    environment:
      - "PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "JAVA_HOME=/opt/java/openjdk"
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US:en"
      - "LC_ALL=en_US.UTF-8"
      - "JAVA_VERSION=jdk-17.0.14+7"
      - "SONARQUBE_HOME=/opt/sonarqube"
      - "SONAR_VERSION=9.9.8.100196"
      - "SQ_DATA_DIR=/opt/sonarqube/data"
      - "SQ_EXTENSIONS_DIR=/opt/sonarqube/extensions"
      - "SQ_LOGS_DIR=/opt/sonarqube/logs"
      - "SQ_TEMP_DIR=/opt/sonarqube/temp"
    hostname: "17e6922b4896"
    image: "sonarqube:lts-community"
    ipc: "private"
    labels:
      org.opencontainers.image.ref.name: "ubuntu"
      org.opencontainers.image.url: "https://github.com/SonarSource/docker-sonarqube"
      org.opencontainers.image.version: "22.04"
    logging:
      driver: "json-file"
      options: {}
    mac_address: "02:42:ac:11:00:02"
    network_mode: "bridge"
    ports:
      - "9000:9000/tcp"
    user: "sonarqube"
    working_dir: "/opt/sonarqube"
version: "3.6"